### ISSUE TITLE
El archivo solicita user and pass para descarga

### ISSUE THREAD

**Issue by gabeeOSLinux** [linuxmobile/dotfiles#1]
Buenos días, estoy siguiendo tu guía para instalar Hypr con tus dotfiles, pero al intentar descargar los mismos desde git, me solicita usuario y contraseña.
¿Esto es así o me estoy equivocando en algo?

Desde ya gracias

Saludos

**Comment by linuxmobile** [comment]
> 

Lo estás descargando mal.
