### ISSUE TITLE
nerd-fonts-complete package not existing

### ISSUE THREAD

**Issue by D3vil0p3r** [linuxmobile/dotfiles#2]
Hello, in the README, where the dependencies from AUR are specified, the `nerd-fonts-complete` package does not exist anymore in AUR. It should be replaced with another one I guess.

**Comment by linuxmobile** [comment]
> Hello, in the README, where the dependencies from AUR are specified, the `nerd-fonts-complete` package does not exist anymore in AUR. It should be replaced with another one I guess.

This is 2 years old dotfiles.
